version: '2'
services:
  mittalramsharaninterstellar-app:
    image: mittalramsharaninterstellar
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mittalramsharaninterstellar-mysql:3306/mittalramsharaninterstellar?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8237:8237
  mittalramsharaninterstellar-mysql:
    extends:
      file: mysql.yml
      service: mittalramsharaninterstellar-mysql
